apiVersion: v1
kind: ConfigMap
metadata:
    name: prometheus-config
data:
    # Include prometheus configuration file, setup to monitor all the
    # Kubernetes pods with the "scrape=true" annotation.
    prometheus.yml: |
        global:
            scrape_interval: 15s
            external_labels:
              cluster: pulsar-cluster
        scrape_configs:
          - job_name: 'prometheus'
            static_configs:
              - targets: ['localhost:9090']

          - job_name: "zookeeper"
            honor_labels: true
            static_configs:
              - targets: ['zookeeper:8000']

          - job_name: "bookkeeper"
            honor_labels: true
            static_configs:
              - targets: ['bookkeeper:8000']

          - job_name: "broker"
            honor_labels: true
            static_configs:
              - targets: ['broker:8080']

          - job_name: "proxy"
            honor_labels: true
            static_configs:
              - targets: ['proxy:8080']

          - job_name: 'kubernetes-pods'
            kubernetes_sd_configs:
              - role: pod

            relabel_configs:
              - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
                action: keep
                regex: true
              - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
                action: replace
                target_label: __metrics_path__
                regex: (.+)
              - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
                action: replace
                regex: ([^:]+)(?::\d+)?;(\d+)
                replacement: $1:$2
                target_label: __address__
              - action: labelmap
                regex: __meta_kubernetes_pod_label_(.+)
              - source_labels: [__meta_kubernetes_namespace]
                action: replace
                target_label: kubernetes_namespace
              - source_labels: [__meta_kubernetes_pod_label_component]
                action: replace
                target_label: job
              - source_labels: [__meta_kubernetes_pod_name]
                action: replace
                target_label: kubernetes_pod_name
---
## PROMOTHEUS - Service
apiVersion: v1
kind: Service
metadata:
    name: prometheus
    labels:
        app: pulsar
        component: prometheus
spec:
    type: NodePort
    ports:
      - name: prometheus
        nodePort: 30003
        port: 9090
        protocol: TCP
    selector:
        app: pulsar
        component: prometheus
---
## PROMOTHEUS - Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
    name: prometheus
spec:
    # Must match template:metadata:labels
    selector:
        matchLabels:
            app: pulsar
            component: prometheus
    replicas: 1
    template:
        metadata:
            labels:
                app: pulsar
                component: prometheus
        spec:
            containers:
              - name: prometheus
                image: prom/prometheus:v1.6.3
                volumeMounts:
                  - name: config-volume
                    mountPath: /etc/prometheus
                  - name: data-volume
                    mountPath: /prometheus
                ports:
                  - containerPort: 9090
            volumes:
              - name: config-volume
                configMap:
                    name: prometheus-config
              - name: data-volume
                emptyDir: {}
---
## GRAFANA - Service
apiVersion: v1
kind: Service
metadata:
    name: grafana
    labels:
        app: pulsar
        component: grafana
spec:
    type: NodePort
    ports:
      - name: grafana
        nodePort: 30004
        port: 3000
        protocol: TCP 
    selector:
        app: pulsar
        component: grafana
---
## GRAFANA - Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
    name: grafana
spec:
    # Must match template:metadata:labels
    selector:
        matchLabels:
            app: pulsar
            component: grafana
    replicas: 1
    template:
        metadata:
            labels:
                app: pulsar
                component: grafana
        spec:
            containers:
              - name: grafana
                image: apachepulsar/pulsar-grafana:latest
                ports:
                  - containerPort: 3000
                env:
                  - name: PROMETHEUS_URL
                    value: http://prometheus:9090/
---
## PULSAR DASHBOARD - Deployment
apiVersion: v1
kind: Service
metadata:
    name: pulsar-dashboard
    labels:
        app: pulsar
        component: dashboard
spec:
    type: NodePort
    ports:
      - name: dashboard
        nodePort: 30005
        port: 80
        protocol: TCP
    selector:
        app: pulsar
        component: dashboard
---
## PULSAR DASHBOARD - Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
    name: pulsar-dashboard
spec:
    # Must match template:metadata:labels
    selector:
        matchLabels:
            app: pulsar
            component: dashboard
    replicas: 1
    template:
        metadata:
            labels:
                app: pulsar
                component: dashboard
        spec:
            containers:
              - name: grafana
                image: apachepulsar/pulsar-dashboard:latest
                ports:
                  - containerPort: 80
                env:
                  - name: SERVICE_URL
                    value: http://broker:8080/
